// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
// ░░░░░░░░▄▀░█▀▄░█▀▀░█▀▀░█░█░█░░░█▀█░█▀▄░░░░░█░░░█▀█░█░█░█▀█░█░█░▀█▀░▀▄░░░░░░░░
// ░░░░░░░▀▄░░█▀▄░█▀▀░█░█░█░█░█░░░█▀█░█▀▄░▀▀▀░█░░░█▀█░░█░░█░█░█░█░░█░░░▄▀░░░░░░░
// ░░░░░░░░░▀░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀░▀░░░░░▀▀▀░▀░▀░░▀░░▀▀▀░▀▀▀░░▀░░▀░░░░░░░░░
// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
// ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
// ┃  *  Copyright (c) 2026, the Regular Layout Authors. This file is part  *  ┃
// ┃  *  of the Regular Layout library, distributed under the terms of the  *  ┃
// ┃  *  [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0). *  ┃
// ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

import type { OverlayMode } from "./types";

/**
 * The prefix to use for `CustomEvent`s generated by `regular-layout`, e.g.
 * `"regular-layout-before-update"`.
 */
export const CUSTOM_EVENT_NAME_PREFIX = "regular-layout";

/**
 * The minimum number of pixels the mouse must move to be considered a drag.
 */
export const MIN_DRAG_DISTANCE = 10;

/**
 * Class name to use for child elements in overlay position (dragging).
 */
export const OVERLAY_CLASSNAME = "overlay";

/**
 * The percentage of the maximum resize distance that will be clamped.
 *
 */
export const MINIMUM_REDISTRIBUTION_SIZE_THRESHOLD = 0.15;

/**
 * Threshold from panel edge that is considered a split vs drop action.
 */
export const SPLIT_EDGE_TOLERANCE = 0.25;

/**
 * Threshold from _container_ edge that is considered a split action on the root
 * node.
 */
export const SPLIT_ROOT_EDGE_TOLERANCE = 0.01;

/**
 * Tolerance threshold for considering two grid track positions as identical.
 *
 * When collecting and deduplicating track positions, any positions closer than
 * this value are treated as the same position to avoid redundant grid tracks.
 */
export const GRID_TRACK_COLLAPSE_TOLERANCE = 0.001;

/**
 * The overlay default behavior.
 */
export const OVERLAY_DEFAULT: OverlayMode = "absolute";

/**
 * Width of split panel dividers in pixels (for hit-test purposes).
 */
export const GRID_DIVIDER_SIZE = 6;
